version: '2'
services:
  ui:
    image: tesutoproject/ui:0.1
    working_dir: /ui
    entrypoint: ng serve --host 0.0.0.0
    ports:
      - "4200:4200"
    volumes:
      - ../ui:/ui
    networks:
      - tesuto-network
networks:
  tesuto-network:
    driver: bridge